# version: '3.8'

services:
  chat-server:
    container_name: chat_server 
    image: mcr.microsoft.com/dotnet/aspnet:8.0
    ports:
      - "59404:80"
    volumes:
      - ./publish:/app
    working_dir: /app
    command: dotnet Chat.dll
    depends_on:
      postgres_db:
        condition: service_healthy
    environment:
      - ConnectionStrings__DefaultConnection=Server=postgres_db;Database=chat_db;User Id=postgres;Password=postgres;
      - ASPNETCORE_URLS=http://+:80
    networks:
      - app-network   # Подключаем сервис к сети

  postgres_db:
    container_name: chat_db
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=chat_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d db"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:       
    driver: bridge